### ISSUE TITLE
Unable to use with HardSourcePlugin

### ISSUE THREAD

**Issue by ChrisSG** [sysgears/persistgraphql-webpack-plugin#16]
Using just the graphql-loader with .graphql files together with HardSourcePlugin is ok on the initial run without cache but fails on subsequent runs. Tha cause is that HardSourceLoader does not save additional attributes to the modules like _graphQLString. So _graphQLString will not be attached to the modules on the subsequent runs.

The error message is:
``
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at writeOut (...\node_modules\webpack\lib\Compiler.js:347:39)
    at require.forEach (...\node_modules\webpack\lib\Compiler.js:361:28)
...
``

Either way there should be a proper error handling when not even one GraphQLString or query is present...

**Comment by larixer** [comment]
@ChrisSG I have reworked the plugin to not attach its meta info during module loading. Plugin now walks the in-memory webpack module tree in `seal` phase, when module loading has been finished and extracts GraphQL queries from each module. I have published the reworked plugin as version 0.5.0 `persistgraphql-webpack-plugin@0.5.0`. Please note that usage has been changed as well, see here for new usage:
https://github.com/sysgears/persistgraphql-webpack-plugin

Please let me know whether version `0.5.0` works with `HardSourcePlugin`

**Comment by ChrisSG** [comment]
Thank you for the quick reply and fix! I will test it now and report back.

**Comment by ChrisSG** [comment]
Ok, it's working now. Great work, thank you! 

Only thing is that i now get an error when using the addTypenames option set to true:

``
if (selectionSet.selections) {
                     ^
TypeError: Cannot read property 'selections' of undefined
    at addTypenameToSelectionSet (...\node_modules\persistgraphql\src\queryTransformers.ts:39:20)
    at ...\node_modules\persistgraphql\src\queryTransformers.ts:65:5
    at Array.forEach (<anonymous>)
    at exports.addTypenameTransformer (...\node_modules\persistgraphql\src\queryTransformers.ts:63:24)
    at ...\node_modules\persistgraphql-webpack-plugin\index.js:80:75
``

Furthermore now the plugin depends on any loader for .gql/.graphql files to be present since you would get following error when no loader for those files is present:

``
Error: Module parse failed: Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
``
If no loader is present.

A solution is to use 'graphql-tag/loader' for anybody else having the problem.

**Comment by larixer** [comment]
@ChrisSG I have added one fix, that might hopefully resolve the problem with addTypenames that you have faced. I'm not 100% sure, because I was not able to reproduce this problem. I have published `0.5.1` version of this plugin with the fix
