### ISSUE TITLE
No error but empty persisted_queries.json if filename option not present

### ISSUE THREAD

**Issue by ChrisSG** [sysgears/persistgraphql-webpack-plugin#17]
If only the graphql-loader is used (may occur aswell with js-loader present but did not test that) and no filename option is present there will be no error but persisted_queries.json will not be generated.

**Comment by larixer** [comment]
@ChrisSG Thanks for reporting. I have tried to reproduce this myself and seems I don't see any issues when you omit `filename` parameter. I have also checked the code and it is highly unlikely that omitting filename will result in some behavior like this. Could you provide detailed reproduction steps or contribute unit test to this repository?

**Comment by larixer** [comment]
@ChrisSG I believe this might be related to your other issue, #16. #16 might be the root cause.

**Comment by ChrisSG** [comment]
Hi again, thank you for the quick response! 
I think it might have been a caching issue as you said, because now I am unabel to reproduce it. I think this issue can be closed for now. Thanks!
