### ISSUE TITLE
broken when using --watch flag

### ISSUE THREAD

**Issue by ChrisSG** [sysgears/persistgraphql-webpack-plugin#20]
When using webpack > 4.6 with the --watch flag it will break with

`(node:12320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'watchFileSystem' of undefined`

I think it's a dependency issue with webpack-virtual-modules rsulting from a chang between webpack 4.6 to 4.7 since is still using persistgraphql-webpack-plugin 1.7.

**For Webpack 4.6:**
https://github.com/sysgears/webpack-virtual-modules/blob/fb8f905f5a9599004b01db38e17213e33e671006/index.js#L50

**For Webpack 4.7:**
https://github.com/sysgears/webpack-virtual-modules/blob/ccca06fe2090c7c6535f5ab21af57c71336c9547/index.js#L50

Could you please update the dependency of webpack-virtual-modules to the latest version?

**Comment by larixer** [comment]
@ChrisSG Updated and published `persistgraphql-webpack-plugin@0.5.2`

Try please

**Comment by ChrisSG** [comment]
Super fast! Seems to be working. Thanks!

**Comment by larixer** [comment]
@ChrisSG No problems. You are welcome
