### ISSUE TITLE
Not usable with graphql-persisted-document-loader

### ISSUE THREAD

**Issue by ChrisSG** [sysgears/persistgraphql-webpack-plugin#21]
Seems the parser is not prepared for receiving a field "documentId" which is provided by the graphql-persisted-document-loader. Webpack startup fails with:

`Error: Invalid AST Node: "4235a050ac0b64114d41d1b22bd4f92b58f95b1e7bb99ccd52a9b696e06aa43f"
    at visit (...\node_modules\graphql\language\visitor.js:250:15)
    at Object.print (...\node_modules\graphql\language\printer.js:15:29)
    at ...\node_modules\persistgraphql-webpack-plugin\index.js:80:42`

**Comment by larixer** [comment]
@ChrisSG Why do you want to use them together?

**Comment by ChrisSG** [comment]
I want persisted queries - not automatic persisted queries. And I want to have code splitting on the client side.

The idea is to use the queries map generated by persistgraphql on the server side and the documentId with apollo-link-persisted-queries on the client. I then would design the server so it only accepts the queries inside the map.

**Comment by larixer** [comment]
Aha, so you want to accept only known persisted queries. I think this is the only use for the persistedgraphql-webpack-plugin. I thought with automatic persisted queries this plugin is no longer needed. Now I understand it is still needed

**Comment by larixer** [comment]
@ChrisSG Yes, but I still don't understand why do you need `graphql-persisted-document-loader` in this setup ?

**Comment by ChrisSG** [comment]
Maybe I am just too inexperienced 😁

The goals are:

- permit only persisted queries
- no other queries allowed
- have code splitting
- generate ids at build time

The last bullet point is the one responsible for using graphql-persisted-document-loader... Maybe I should just skip this.

Any idea how to achieve all of this?

**Comment by larixer** [comment]
@ChrisSG This plugin generates query ids at build time, so I'm not sure why you need to add `graphql-persisted-document-loader`.

**Comment by larixer** [comment]
@ChrisSG Ah, I understood, because you want to use `apollo-link-persisted-queries` and it requires `documentId`

**Comment by ChrisSG** [comment]
Ah, sorry for the missing info here... 😅

It's not that I definitely need apollo-link-persisted-queries. It could be another solution as well but it needs to support code splitting.

**Comment by larixer** [comment]
@ChrisSG I think it is possible to make this plugin compatible with `graphql-persisted-document-loader`, it needs to ignore doc.documentId = ... assignment when parsing AST. I'm too busy at the moment to work on this, but I would be happy to accept Pull Request.

**Comment by ChrisSG** [comment]
I could do it. Where do I have to look at? Do you have a hint for me?

Round here? https://github.com/sysgears/persistgraphql-webpack-plugin/blob/e8a25819c8e7610cc0dcd762ae353757e0ad89af/index.js#L104

Or maybe there is an easy way to generate the map without the client?

**Comment by larixer** [comment]
@ChrisSG You can add `graphql-persisted-document-loader` into devDependencies, then modify this test to include it:
https://github.com/sysgears/persistgraphql-webpack-plugin/blob/master/test/index.js#L31-L67
And add `console.log` to see whats happening inside plugin

**Comment by ChrisSG** [comment]
Seems to be a issue with `graphql-persisted-document-loader`

See https://github.com/leoasis/graphql-persisted-document-loader/issues/3

**Comment by larixer** [comment]
@ChrisSG I see, thank you for update

**Comment by larixer** [comment]
@ChrisSG If you have updated test with `graphql-persisted-document-loader` please open Pull Request

**Comment by ChrisSG** [comment]
I have done it. But are you sure  a PR makes any sense, as the error lies in the other plugin?

**Comment by larixer** [comment]
@ChrisSG Sure, it does makes sense. If you look at the source of this plugin - it has all sorts of workarounds to fix problems in other plugins and libraries. I think this problem can be worked around too. It all depends on the responsiveness of the devs behind `graphql-persisted-document-loader`

**Comment by larixer** [comment]
@ChrisSG See the commit above. New version of plugin with workaround included published as `persistgraphql-webpack-plugin@0.5.3`

**Comment by larixer** [comment]
Hey @ChrisSG Did you have a chance to try latest version of the plugin?

**Comment by ChrisSG** [comment]
It is working with my PR https://github.com/leoasis/graphql-persisted-document-loader/pull/4 for graphql-persisted-document-loader. But the PR is not accepted yet.

Also we need a new issue for the ID in persistgraphql-webpack-plugin not being the same as the one of the apollo plugins / graphql-persisted-document-loader. persistgraphql-webpack-plugin uses an index, graphql-persisted-document-loade uses sha256 hash...

See https://github.com/sysgears/persistgraphql-webpack-plugin/issues/23

**Comment by larixer** [comment]
@ChrisSG The last version of this plugin should work without your PR, see commit:
https://github.com/sysgears/persistgraphql-webpack-plugin/commit/5235a14f4fe85692261bdc565ba1a05c7d6e5671
