### ISSUE TITLE
Should have option to use a sha256 hash like other plugins (graphql-persisted-document-loader)

### ISSUE THREAD

**Issue by ChrisSG** [sysgears/persistgraphql-webpack-plugin#23]
A option should be implemented to provide an arbitrary funktion for generating the IDs of the queries e.g. sha256 etc. see https://github.com/leoasis/graphql-persisted-document-loader/blob/64ef3012bf63c9d608421e48b3afa056117c4a38/index.js#L92

**Comment by larixer** [comment]
@ChrisSG See commit above. Published as version `0.5.4` of the plugin. Now query ids are SHA-256 hashes by default.
