### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by sebas5384** [sysgears/persistgraphql-webpack-plugin#27]
Hi there!

I have the same issue as https://github.com/sysgears/persistgraphql-webpack-plugin/issues/16 and I'm using it with Next.js 5.1.0

Any ideia what could be?

**Comment by larixer** [comment]
@sebas5384 Please attach stack trace of the error that you see.
