### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by myyellowshoe** [sysgears/persistgraphql-webpack-plugin#5]
I think there might be an issue as I'm still on webpack 1, and I think the documentation is set for webpack 2. I don't consider myself a webpack expert, so that might also be the case that I'm making a silly mistake.

I'm getting the following error.
```
Error in (webpack)-dev-server/client?/
Module not found: Error: Cannot resolve module 'persistgraphql-webpack-plugin/js-loader'
```
Here is my config setup:

```    loaders: [
      // Process JS with Babel.
      {
        test: /\.(js|jsx)$/,
        include: paths.appSrc,
        loader: 'babel',
        query: require('./babel.dev'),
      },
      {
        test: /\.jsx?$/,
        loader: 'persistgraphql-webpack-plugin/js-loader',
      },
      {
        test: /\.(graphql|gql)$/,
        loader: 'graphql-tag/loader',
      },
      {
        test: /\.(graphql|gql)$/,
        loader: 'persistgraphql-webpack-plugin/graphql-loader',
      },

........
  plugins: [
   ...
    new PersistGraphQLPlugin({ filename: 'persisted_queries.json', moduleName: path.resolve('node_modules/persisted_queries.json') }),
  ]
    
```

What could be the issue here?

**Comment by larixer** [comment]
@myyellowshoe Thanks for reporting. This plugin has been tested with Webpack 2 only. Though I believe it doesn't depend on Webpack 2 and should be adjustable to work with Webpack 1 without much effort. I will try to look at this during next few days and if you happen to have some open source project with Webpack 1 and configured to use this plugin, so that I can clone it and use as playground it would be helpful

**Comment by myyellowshoe** [comment]
@vlasenko Gotcha, no worries. In this case I'm getting ready to upgrade to webpack 2 but I thought it would be helpful for others as well who wouldn't be able to upgrade. Unfortunately the project I'm working on with this is a private repo, otherwise, I'd be all for it!

**Comment by larixer** [comment]
@myyellowshoe Webpack 1 should be supported starting from version `0.3.0` of this plugin. Please also read instructions - how to configure this plugin with Webpack 1 here:
https://github.com/sysgears/persistgraphql-webpack-plugin

Please report back if something is not working as expected
